# permissions for end users to edit rocketmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rocketmq-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rocketmq-operator
    app.kubernetes.io/part-of: rocketmq-operator
    app.kubernetes.io/managed-by: kustomize
  name: rocketmq-editor-role
rules:
- apiGroups:
  - addons.erda.cloud
  resources:
  - rocketmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.erda.cloud
  resources:
  - rocketmqs/status
  verbs:
  - get
