---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - addons.erda.cloud
  resources:
  - rocketmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.erda.cloud
  resources:
  - rocketmqs/finalizers
  verbs:
  - update
- apiGroups:
  - addons.erda.cloud
  resources:
  - rocketmqs/status
  verbs:
  - get
  - patch
  - update
